use_frameworks!
target 'iOSnier' do
    pod 'RxSwift' , '~>4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'Alamofire'
    pod 'SnapKit', '~> 4.0.0'
    pod 'Kingfisher'
    pod 'YogaKit'
    pod 'MarkdownView'
    pod 'QXKit'
end
